TP.EF/TP4.EF.MVC/Models/ErrorView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP4.EF.MVC.Models
{
    public class ErrorView
    {
        public List<string> listadoDeErrores = new List<string>();

    }
}

TP.EF/TP4.EF.MVC/Models/ShippersView.cs
using System.ComponentModel.DataAnnotations;

namespace TP4.EF.MVC.Models
{
    public class ShippersView
    {
        public int ShipperID { get; set; }
        [Required(ErrorMessage = "Debe indicarse un nombre de la compañía")]
        [StringLength(40, ErrorMessage = "El nombre de la empresa no debe superar los 40 caracteres")]
        public string CompanyName { get; set; }
        [StringLength(24, ErrorMessage = "El teléfono no debe superar los 40 caracteres")]
        public string Phone { get; set; }
        public string Modificar { get; set; }
    }
}

TP.EF/TP4.EF.MVC/Models/StarWarsCharacterView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TP4.EF.MVC.Models
{
    public class StarWarsCharacterView
    {
        // se toman 3 parámetros para simplificar el ejemplo
        public string Name { get; set; }
        public string Mass { get; set; }
        public string Height { get; set; }

    }
}

TP.EF/TP4.EF.MVC/Controllers/ErrorController.cs
using System;
using System.Web.Mvc;
using TP4.EF.MVC.Models;

namespace TP4.EF.MVC.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index(string error)
        {
            ErrorView errorView = new ErrorView();
            errorView.listadoDeErrores.Add(error);
            return View(errorView);
        }
    }
}

TP.EF/TP4.EF.MVC/Controllers/ShippersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP4.EF.Logic;
using TP4.EF.Entities;
using TP4.EF.MVC.Models;

namespace TP4.EF.MVC.Controllers
{
    public class ShippersController : Controller
    {
        ShippersLogic shippersLogic = new ShippersLogic();
        // GET: Shippers
        public ActionResult Index()
        {
            List<ShippersView> shippersViews = new List<ShippersView>();
            try
            {
                List<Shippers> shippers = shippersLogic.GetAll();
                shippersViews = shippers.Select(s => new ShippersView
                {
                    ShipperID = s.ShipperID,
                    CompanyName = s.CompanyName,
                    Phone = s.Phone
                }).ToList();
                return View(shippersViews);
            }


            catch(Exception e) 
            {
                string error = e.Message.ToString();
                return RedirectToAction("Index", "Error",new { error = error });
            }
            
        }

        /*[HttpPost]
        public ActionResult Index()
        {
            List<Shippers> shippers = shippersLogic.GetAll();
            List<ShippersView> shippersViews = shippers.Select(s => new ShippersView
            {
                ShipperID = s.ShipperID,
                CompanyName = s.CompanyName,
                Phone = s.Phone
            }).ToList();

            return View(shippersViews);
        }*/

        [HttpGet]
        public ActionResult InsertUpdate(ShippersView shippersView)
        {
             return View(shippersView);
        }
       
        [HttpPost]
        public ActionResult InsertUpdate(ShippersView shippersView, string insertUpdate)
        {
            if(shippersView.Modificar=="Mod")
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                    Shippers shipperEntity = new Shippers
                    {
                        ShipperID=shippersView.ShipperID,
                        CompanyName = shippersView.CompanyName,
                        Phone = shippersView.Phone
                    };
                    shippersLogic.Update(shipperEntity);
                    return RedirectToAction("Index");
                    }
                }
                catch
                {
                    return RedirectToAction("Index", "Error");
                }
            }
            else
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        Shippers shipperEntity = new Shippers
                        {
                            CompanyName = shippersView.CompanyName,
                            Phone = shippersView.Phone
                        };

                        shippersLogic.Add(shipperEntity);

                        return RedirectToAction("Index");

                    }
                }
                catch
                {
                    return RedirectToAction("Index", "Error");
                }

            }

            return View(shippersView);
        }

        public ActionResult Delete(int id)
        {
            shippersLogic.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

TP.EF/TP4.EF.MVC/Controllers/StarWarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using TP4.EF.MVC.Models;
using Newtonsoft.Json.Linq;

namespace TP4.EF.MVC.Controllers
{
    public class StarWarsController : Controller
    {
        // GET: StarWars
        string Baseurl = "https://swapi.dev/api";
        public async Task<ActionResult> Index()
        {
            List<StarWarsCharacterView>swCharacter = new List<StarWarsCharacterView>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage Res = await client.GetAsync("api/people");
                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    JObject objResponse1 = (JObject)JsonConvert.DeserializeObject(EmpResponse);
               
                    foreach (var sub_obj in objResponse1["results"])
                    {
                        JObject jswchar = sub_obj as JObject;
                        StarWarsCharacterView swchar = jswchar.ToObject<StarWarsCharacterView>();
                        swCharacter.Add(swchar);
                    }
                }
                return View(swCharacter);
            }
        }
      
    }
}

TP.EF/TP4.EF.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TP7 - ABM Shippers", "Index", "Shippers", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.ActionLink("TP8 - Consumo Star Wars API", "Index", "StarWars", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
          
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TP.EF/TP4.EF.MVC/Views/Shippers/Index.cshtml
@model List<TP4.EF.MVC.Models.ShippersView>

@{
    ViewBag.Title = "Region Page";
}

<h1>Shippers index</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col"> Id Shipper   </th>
            <th scope="col"> Nombre de la compañía   </th>
            <th scope="col"> Teléfono </th>
            <th scope="col"> Editar </th>   
            <th scope="col"> Eliminar </th>
        </tr>
    </thead>
    @foreach (TP4.EF.MVC.Models.ShippersView shipperView in Model)
    {
        <tr>
            <td scope="row">  @shipperView.ShipperID   </td>
            <td scope="row">  @shipperView.CompanyName    </td>
            <td scope="row"> @shipperView.Phone </td>
            <td scope="row"> @Html.ActionLink("Editar shipper", "InsertUpdate", new TP4.EF.MVC.Models.ShippersView { ShipperID = shipperView.ShipperID, CompanyName = shipperView.CompanyName, Phone = shipperView.Phone, Modificar = "Mod" }, new { onclick = "return confirm('Está seguro de editar el shipper?')" }) </td>
            <td scope="row"> @Html.ActionLink("Eliminar shipper", "Delete", new { id = shipperView.ShipperID }, new { onclick = "return confirm('Está seguro de borrar el shipper?')" }) </td>
        </tr>
    }
</table>

<div>@Html.ActionLink("Insertar nuevo shipper", "InsertUpdate", "Shippers")</div>

TP.EF/TP4.EF.MVC/Views/Shippers/InsertUpdate.cshtml
@model TP4.EF.MVC.Models.ShippersView

@{
    ViewBag.Title = "Shippers Page";
}

@if (Model.Modificar == "Mod")
{
    <h1>Vista para modificar shippers</h1>
}
else
{
    <h1>Vista para insertar shippers</h1>
}

<br />

<div class="form-group">
    @using (Html.BeginForm("InsertUpdate", "Shippers", FormMethod.Post))
    {

        @Html.HiddenFor(s => s.ShipperID)
        @Html.HiddenFor(s => s.Modificar)

        if (Model.Modificar == "Mod")
        {
            <label> Id del shipper a editar: </label>
            <br />
            @Html.DisplayFor(s => s.ShipperID)
            <br />
        }

        <label> Nombre de la compañía: </label>
        <br />
        @Html.EditorFor(s => s.CompanyName)@Html.ValidationMessageFor(m => m.CompanyName, "", new { @class = "text-danger" })
        <br />
        <label> Teléfono: </label>
        <br />
        @Html.EditorFor(s => s.Phone) @Html.ValidationMessageFor(s => s.Phone, "", new { @class = "text-danger" })
        <br />
        <br />
        <input type="submit" name="" value="Guardar" class="btn-success" />

    }
</div>

TP.EF/TP4.EF.MVC/Views/StarWars/Index.cshtml
@model IEnumerable<TP4.EF.MVC.Models.StarWarsCharacterView>

@{
    ViewBag.Title = "Star Wars API";
}

<h3>Consumo de Star Wars Api - categoría "people"  </h3>
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mass)
        </th>
      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mass)
        </td>
        
    </tr>
}

</table>